/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GoRouteImport } from './routes/go'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PHandleRouteImport } from './routes/p/$handle'
import { Route as AuthenticatedTrackerRouteImport } from './routes/_authenticated/tracker'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSalaryRouteImport } from './routes/_authenticated/salary'
import { Route as AuthenticatedRoadmapRouteImport } from './routes/_authenticated/roadmap'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOutreachRouteImport } from './routes/_authenticated/outreach'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedLearningRouteImport } from './routes/_authenticated/learning'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoachRouteImport } from './routes/_authenticated/coach'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAgentRouteImport } from './routes/_authenticated/agent'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedResumesIndexRouteImport } from './routes/_authenticated/resumes.index'
import { Route as AuthenticatedJobsIndexRouteImport } from './routes/_authenticated/jobs.index'
import { Route as AuthenticatedApplicationsIndexRouteImport } from './routes/_authenticated/applications.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedResumesResumeIdRouteImport } from './routes/_authenticated/resumes.$resumeId'
import { Route as AuthenticatedResumeReviewResumeIdRouteImport } from './routes/_authenticated/resume-review.$resumeId'
import { Route as AuthenticatedJobsSavedRouteImport } from './routes/_authenticated/jobs.saved'
import { Route as AuthenticatedJobsCollectionsRouteImport } from './routes/_authenticated/jobs.collections'
import { Route as AuthenticatedJobsJobIdRouteImport } from './routes/_authenticated/jobs.$jobId'
import { Route as AuthenticatedInvoicePaymentIdRouteImport } from './routes/_authenticated/invoice.$paymentId'
import { Route as AuthenticatedInterviewSimulatorRouteImport } from './routes/_authenticated/interview.simulator'
import { Route as AuthenticatedApplicationsWorkspaceIdRouteImport } from './routes/_authenticated/applications.$workspaceId'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminJobsRouteImport } from './routes/_authenticated/admin.jobs'
import { Route as AuthenticatedAdminHealthRouteImport } from './routes/_authenticated/admin.health'
import { Route as AuthenticatedAdminEmailsRouteImport } from './routes/_authenticated/admin.emails'
import { Route as AuthenticatedAdminBillingRouteImport } from './routes/_authenticated/admin.billing'
import { Route as AuthenticatedAdminAutoApplyRouteImport } from './routes/_authenticated/admin.auto-apply'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminAiRouteImport } from './routes/_authenticated/admin.ai'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksWeeklySummaryRouteImport } from './routes/api/public/hooks/weekly-summary'
import { Route as ApiPublicHooksRefreshMatchesRouteImport } from './routes/api/public/hooks/refresh-matches'
import { Route as ApiPublicHooksRazorpayWebhookRouteImport } from './routes/api/public/hooks/razorpay-webhook'
import { Route as ApiPublicHooksEmailDiagnosticRouteImport } from './routes/api/public/hooks/email-diagnostic'
import { Route as ApiPublicHooksDiscoverJobsRouteImport } from './routes/api/public/hooks/discover-jobs'
import { Route as ApiPublicHooksAutoApplyEventsRouteImport } from './routes/api/public/hooks/auto-apply-events'
import { Route as AuthenticatedJobsCollectionsCollectionIdRouteImport } from './routes/_authenticated/jobs.collections.$collectionId'
import { Route as AuthenticatedApplicationsWorkspaceIdAgentRouteImport } from './routes/_authenticated/applications.$workspaceId.agent'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GoRoute = GoRouteImport.update({
  id: '/go',
  path: '/go',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PHandleRoute = PHandleRouteImport.update({
  id: '/p/$handle',
  path: '/p/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrackerRoute = AuthenticatedTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalaryRoute = AuthenticatedSalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRoadmapRoute = AuthenticatedRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOutreachRoute = AuthenticatedOutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLearningRoute = AuthenticatedLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCoachRoute = AuthenticatedCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentRoute = AuthenticatedAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResumesIndexRoute =
  AuthenticatedResumesIndexRouteImport.update({
    id: '/resumes/',
    path: '/resumes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobsIndexRoute = AuthenticatedJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplicationsIndexRoute =
  AuthenticatedApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedResumesResumeIdRoute =
  AuthenticatedResumesResumeIdRouteImport.update({
    id: '/resumes/$resumeId',
    path: '/resumes/$resumeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResumeReviewResumeIdRoute =
  AuthenticatedResumeReviewResumeIdRouteImport.update({
    id: '/resume-review/$resumeId',
    path: '/resume-review/$resumeId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobsSavedRoute = AuthenticatedJobsSavedRouteImport.update({
  id: '/jobs/saved',
  path: '/jobs/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobsCollectionsRoute =
  AuthenticatedJobsCollectionsRouteImport.update({
    id: '/jobs/collections',
    path: '/jobs/collections',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobsJobIdRoute = AuthenticatedJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicePaymentIdRoute =
  AuthenticatedInvoicePaymentIdRouteImport.update({
    id: '/invoice/$paymentId',
    path: '/invoice/$paymentId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInterviewSimulatorRoute =
  AuthenticatedInterviewSimulatorRouteImport.update({
    id: '/interview/simulator',
    path: '/interview/simulator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApplicationsWorkspaceIdRoute =
  AuthenticatedApplicationsWorkspaceIdRouteImport.update({
    id: '/applications/$workspaceId',
    path: '/applications/$workspaceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminJobsRoute = AuthenticatedAdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminHealthRoute =
  AuthenticatedAdminHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEmailsRoute =
  AuthenticatedAdminEmailsRouteImport.update({
    id: '/emails',
    path: '/emails',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBillingRoute =
  AuthenticatedAdminBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAutoApplyRoute =
  AuthenticatedAdminAutoApplyRouteImport.update({
    id: '/auto-apply',
    path: '/auto-apply',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAiRoute = AuthenticatedAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksWeeklySummaryRoute =
  ApiPublicHooksWeeklySummaryRouteImport.update({
    id: '/api/public/hooks/weekly-summary',
    path: '/api/public/hooks/weekly-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRefreshMatchesRoute =
  ApiPublicHooksRefreshMatchesRouteImport.update({
    id: '/api/public/hooks/refresh-matches',
    path: '/api/public/hooks/refresh-matches',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRazorpayWebhookRoute =
  ApiPublicHooksRazorpayWebhookRouteImport.update({
    id: '/api/public/hooks/razorpay-webhook',
    path: '/api/public/hooks/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEmailDiagnosticRoute =
  ApiPublicHooksEmailDiagnosticRouteImport.update({
    id: '/api/public/hooks/email-diagnostic',
    path: '/api/public/hooks/email-diagnostic',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDiscoverJobsRoute =
  ApiPublicHooksDiscoverJobsRouteImport.update({
    id: '/api/public/hooks/discover-jobs',
    path: '/api/public/hooks/discover-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoApplyEventsRoute =
  ApiPublicHooksAutoApplyEventsRouteImport.update({
    id: '/api/public/hooks/auto-apply-events',
    path: '/api/public/hooks/auto-apply-events',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedJobsCollectionsCollectionIdRoute =
  AuthenticatedJobsCollectionsCollectionIdRouteImport.update({
    id: '/$collectionId',
    path: '/$collectionId',
    getParentRoute: () => AuthenticatedJobsCollectionsRoute,
  } as any)
const AuthenticatedApplicationsWorkspaceIdAgentRoute =
  AuthenticatedApplicationsWorkspaceIdAgentRouteImport.update({
    id: '/agent',
    path: '/agent',
    getParentRoute: () => AuthenticatedApplicationsWorkspaceIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/go': typeof GoRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/agent': typeof AuthenticatedAgentRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/chat': typeof AuthenticatedChatRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/learning': typeof AuthenticatedLearningRoute
  '/me': typeof AuthenticatedMeRoute
  '/outreach': typeof AuthenticatedOutreachRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/salary': typeof AuthenticatedSalaryRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tracker': typeof AuthenticatedTrackerRoute
  '/p/$handle': typeof PHandleRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/auto-apply': typeof AuthenticatedAdminAutoApplyRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/health': typeof AuthenticatedAdminHealthRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/applications/$workspaceId': typeof AuthenticatedApplicationsWorkspaceIdRouteWithChildren
  '/interview/simulator': typeof AuthenticatedInterviewSimulatorRoute
  '/invoice/$paymentId': typeof AuthenticatedInvoicePaymentIdRoute
  '/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/jobs/collections': typeof AuthenticatedJobsCollectionsRouteWithChildren
  '/jobs/saved': typeof AuthenticatedJobsSavedRoute
  '/resume-review/$resumeId': typeof AuthenticatedResumeReviewResumeIdRoute
  '/resumes/$resumeId': typeof AuthenticatedResumesResumeIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/jobs/': typeof AuthenticatedJobsIndexRoute
  '/resumes/': typeof AuthenticatedResumesIndexRoute
  '/applications/$workspaceId/agent': typeof AuthenticatedApplicationsWorkspaceIdAgentRoute
  '/jobs/collections/$collectionId': typeof AuthenticatedJobsCollectionsCollectionIdRoute
  '/api/public/hooks/auto-apply-events': typeof ApiPublicHooksAutoApplyEventsRoute
  '/api/public/hooks/discover-jobs': typeof ApiPublicHooksDiscoverJobsRoute
  '/api/public/hooks/email-diagnostic': typeof ApiPublicHooksEmailDiagnosticRoute
  '/api/public/hooks/razorpay-webhook': typeof ApiPublicHooksRazorpayWebhookRoute
  '/api/public/hooks/refresh-matches': typeof ApiPublicHooksRefreshMatchesRoute
  '/api/public/hooks/weekly-summary': typeof ApiPublicHooksWeeklySummaryRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/go': typeof GoRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/agent': typeof AuthenticatedAgentRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/chat': typeof AuthenticatedChatRoute
  '/coach': typeof AuthenticatedCoachRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/learning': typeof AuthenticatedLearningRoute
  '/me': typeof AuthenticatedMeRoute
  '/outreach': typeof AuthenticatedOutreachRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/roadmap': typeof AuthenticatedRoadmapRoute
  '/salary': typeof AuthenticatedSalaryRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tracker': typeof AuthenticatedTrackerRoute
  '/p/$handle': typeof PHandleRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/auto-apply': typeof AuthenticatedAdminAutoApplyRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/admin/health': typeof AuthenticatedAdminHealthRoute
  '/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/applications/$workspaceId': typeof AuthenticatedApplicationsWorkspaceIdRouteWithChildren
  '/interview/simulator': typeof AuthenticatedInterviewSimulatorRoute
  '/invoice/$paymentId': typeof AuthenticatedInvoicePaymentIdRoute
  '/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/jobs/collections': typeof AuthenticatedJobsCollectionsRouteWithChildren
  '/jobs/saved': typeof AuthenticatedJobsSavedRoute
  '/resume-review/$resumeId': typeof AuthenticatedResumeReviewResumeIdRoute
  '/resumes/$resumeId': typeof AuthenticatedResumesResumeIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/applications': typeof AuthenticatedApplicationsIndexRoute
  '/jobs': typeof AuthenticatedJobsIndexRoute
  '/resumes': typeof AuthenticatedResumesIndexRoute
  '/applications/$workspaceId/agent': typeof AuthenticatedApplicationsWorkspaceIdAgentRoute
  '/jobs/collections/$collectionId': typeof AuthenticatedJobsCollectionsCollectionIdRoute
  '/api/public/hooks/auto-apply-events': typeof ApiPublicHooksAutoApplyEventsRoute
  '/api/public/hooks/discover-jobs': typeof ApiPublicHooksDiscoverJobsRoute
  '/api/public/hooks/email-diagnostic': typeof ApiPublicHooksEmailDiagnosticRoute
  '/api/public/hooks/razorpay-webhook': typeof ApiPublicHooksRazorpayWebhookRoute
  '/api/public/hooks/refresh-matches': typeof ApiPublicHooksRefreshMatchesRoute
  '/api/public/hooks/weekly-summary': typeof ApiPublicHooksWeeklySummaryRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/go': typeof GoRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/agent': typeof AuthenticatedAgentRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/coach': typeof AuthenticatedCoachRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/learning': typeof AuthenticatedLearningRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/outreach': typeof AuthenticatedOutreachRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/roadmap': typeof AuthenticatedRoadmapRoute
  '/_authenticated/salary': typeof AuthenticatedSalaryRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tracker': typeof AuthenticatedTrackerRoute
  '/p/$handle': typeof PHandleRoute
  '/_authenticated/admin/ai': typeof AuthenticatedAdminAiRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/auto-apply': typeof AuthenticatedAdminAutoApplyRoute
  '/_authenticated/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/_authenticated/admin/emails': typeof AuthenticatedAdminEmailsRoute
  '/_authenticated/admin/health': typeof AuthenticatedAdminHealthRoute
  '/_authenticated/admin/jobs': typeof AuthenticatedAdminJobsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/applications/$workspaceId': typeof AuthenticatedApplicationsWorkspaceIdRouteWithChildren
  '/_authenticated/interview/simulator': typeof AuthenticatedInterviewSimulatorRoute
  '/_authenticated/invoice/$paymentId': typeof AuthenticatedInvoicePaymentIdRoute
  '/_authenticated/jobs/$jobId': typeof AuthenticatedJobsJobIdRoute
  '/_authenticated/jobs/collections': typeof AuthenticatedJobsCollectionsRouteWithChildren
  '/_authenticated/jobs/saved': typeof AuthenticatedJobsSavedRoute
  '/_authenticated/resume-review/$resumeId': typeof AuthenticatedResumeReviewResumeIdRoute
  '/_authenticated/resumes/$resumeId': typeof AuthenticatedResumesResumeIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/applications/': typeof AuthenticatedApplicationsIndexRoute
  '/_authenticated/jobs/': typeof AuthenticatedJobsIndexRoute
  '/_authenticated/resumes/': typeof AuthenticatedResumesIndexRoute
  '/_authenticated/applications/$workspaceId/agent': typeof AuthenticatedApplicationsWorkspaceIdAgentRoute
  '/_authenticated/jobs/collections/$collectionId': typeof AuthenticatedJobsCollectionsCollectionIdRoute
  '/api/public/hooks/auto-apply-events': typeof ApiPublicHooksAutoApplyEventsRoute
  '/api/public/hooks/discover-jobs': typeof ApiPublicHooksDiscoverJobsRoute
  '/api/public/hooks/email-diagnostic': typeof ApiPublicHooksEmailDiagnosticRoute
  '/api/public/hooks/razorpay-webhook': typeof ApiPublicHooksRazorpayWebhookRoute
  '/api/public/hooks/refresh-matches': typeof ApiPublicHooksRefreshMatchesRoute
  '/api/public/hooks/weekly-summary': typeof ApiPublicHooksWeeklySummaryRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/go'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/agent'
    | '/analytics'
    | '/billing'
    | '/chat'
    | '/coach'
    | '/dashboard'
    | '/learning'
    | '/me'
    | '/outreach'
    | '/profile'
    | '/roadmap'
    | '/salary'
    | '/settings'
    | '/tracker'
    | '/p/$handle'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/auto-apply'
    | '/admin/billing'
    | '/admin/emails'
    | '/admin/health'
    | '/admin/jobs'
    | '/admin/users'
    | '/applications/$workspaceId'
    | '/interview/simulator'
    | '/invoice/$paymentId'
    | '/jobs/$jobId'
    | '/jobs/collections'
    | '/jobs/saved'
    | '/resume-review/$resumeId'
    | '/resumes/$resumeId'
    | '/admin/'
    | '/applications/'
    | '/jobs/'
    | '/resumes/'
    | '/applications/$workspaceId/agent'
    | '/jobs/collections/$collectionId'
    | '/api/public/hooks/auto-apply-events'
    | '/api/public/hooks/discover-jobs'
    | '/api/public/hooks/email-diagnostic'
    | '/api/public/hooks/razorpay-webhook'
    | '/api/public/hooks/refresh-matches'
    | '/api/public/hooks/weekly-summary'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/go'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/agent'
    | '/analytics'
    | '/billing'
    | '/chat'
    | '/coach'
    | '/dashboard'
    | '/learning'
    | '/me'
    | '/outreach'
    | '/profile'
    | '/roadmap'
    | '/salary'
    | '/settings'
    | '/tracker'
    | '/p/$handle'
    | '/admin/ai'
    | '/admin/analytics'
    | '/admin/auto-apply'
    | '/admin/billing'
    | '/admin/emails'
    | '/admin/health'
    | '/admin/jobs'
    | '/admin/users'
    | '/applications/$workspaceId'
    | '/interview/simulator'
    | '/invoice/$paymentId'
    | '/jobs/$jobId'
    | '/jobs/collections'
    | '/jobs/saved'
    | '/resume-review/$resumeId'
    | '/resumes/$resumeId'
    | '/admin'
    | '/applications'
    | '/jobs'
    | '/resumes'
    | '/applications/$workspaceId/agent'
    | '/jobs/collections/$collectionId'
    | '/api/public/hooks/auto-apply-events'
    | '/api/public/hooks/discover-jobs'
    | '/api/public/hooks/email-diagnostic'
    | '/api/public/hooks/razorpay-webhook'
    | '/api/public/hooks/refresh-matches'
    | '/api/public/hooks/weekly-summary'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contact'
    | '/go'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/agent'
    | '/_authenticated/analytics'
    | '/_authenticated/billing'
    | '/_authenticated/chat'
    | '/_authenticated/coach'
    | '/_authenticated/dashboard'
    | '/_authenticated/learning'
    | '/_authenticated/me'
    | '/_authenticated/outreach'
    | '/_authenticated/profile'
    | '/_authenticated/roadmap'
    | '/_authenticated/salary'
    | '/_authenticated/settings'
    | '/_authenticated/tracker'
    | '/p/$handle'
    | '/_authenticated/admin/ai'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/auto-apply'
    | '/_authenticated/admin/billing'
    | '/_authenticated/admin/emails'
    | '/_authenticated/admin/health'
    | '/_authenticated/admin/jobs'
    | '/_authenticated/admin/users'
    | '/_authenticated/applications/$workspaceId'
    | '/_authenticated/interview/simulator'
    | '/_authenticated/invoice/$paymentId'
    | '/_authenticated/jobs/$jobId'
    | '/_authenticated/jobs/collections'
    | '/_authenticated/jobs/saved'
    | '/_authenticated/resume-review/$resumeId'
    | '/_authenticated/resumes/$resumeId'
    | '/_authenticated/admin/'
    | '/_authenticated/applications/'
    | '/_authenticated/jobs/'
    | '/_authenticated/resumes/'
    | '/_authenticated/applications/$workspaceId/agent'
    | '/_authenticated/jobs/collections/$collectionId'
    | '/api/public/hooks/auto-apply-events'
    | '/api/public/hooks/discover-jobs'
    | '/api/public/hooks/email-diagnostic'
    | '/api/public/hooks/razorpay-webhook'
    | '/api/public/hooks/refresh-matches'
    | '/api/public/hooks/weekly-summary'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  GoRoute: typeof GoRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  PHandleRoute: typeof PHandleRoute
  ApiPublicHooksAutoApplyEventsRoute: typeof ApiPublicHooksAutoApplyEventsRoute
  ApiPublicHooksDiscoverJobsRoute: typeof ApiPublicHooksDiscoverJobsRoute
  ApiPublicHooksEmailDiagnosticRoute: typeof ApiPublicHooksEmailDiagnosticRoute
  ApiPublicHooksRazorpayWebhookRoute: typeof ApiPublicHooksRazorpayWebhookRoute
  ApiPublicHooksRefreshMatchesRoute: typeof ApiPublicHooksRefreshMatchesRoute
  ApiPublicHooksWeeklySummaryRoute: typeof ApiPublicHooksWeeklySummaryRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go': {
      id: '/go'
      path: '/go'
      fullPath: '/go'
      preLoaderRoute: typeof GoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$handle': {
      id: '/p/$handle'
      path: '/p/$handle'
      fullPath: '/p/$handle'
      preLoaderRoute: typeof PHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tracker': {
      id: '/_authenticated/tracker'
      path: '/tracker'
      fullPath: '/tracker'
      preLoaderRoute: typeof AuthenticatedTrackerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/salary': {
      id: '/_authenticated/salary'
      path: '/salary'
      fullPath: '/salary'
      preLoaderRoute: typeof AuthenticatedSalaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roadmap': {
      id: '/_authenticated/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof AuthenticatedRoadmapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/outreach': {
      id: '/_authenticated/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof AuthenticatedOutreachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learning': {
      id: '/_authenticated/learning'
      path: '/learning'
      fullPath: '/learning'
      preLoaderRoute: typeof AuthenticatedLearningRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/coach': {
      id: '/_authenticated/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AuthenticatedCoachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agent': {
      id: '/_authenticated/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AuthenticatedAgentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resumes/': {
      id: '/_authenticated/resumes/'
      path: '/resumes'
      fullPath: '/resumes/'
      preLoaderRoute: typeof AuthenticatedResumesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/': {
      id: '/_authenticated/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AuthenticatedJobsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications/': {
      id: '/_authenticated/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof AuthenticatedApplicationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/resumes/$resumeId': {
      id: '/_authenticated/resumes/$resumeId'
      path: '/resumes/$resumeId'
      fullPath: '/resumes/$resumeId'
      preLoaderRoute: typeof AuthenticatedResumesResumeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/resume-review/$resumeId': {
      id: '/_authenticated/resume-review/$resumeId'
      path: '/resume-review/$resumeId'
      fullPath: '/resume-review/$resumeId'
      preLoaderRoute: typeof AuthenticatedResumeReviewResumeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/saved': {
      id: '/_authenticated/jobs/saved'
      path: '/jobs/saved'
      fullPath: '/jobs/saved'
      preLoaderRoute: typeof AuthenticatedJobsSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/collections': {
      id: '/_authenticated/jobs/collections'
      path: '/jobs/collections'
      fullPath: '/jobs/collections'
      preLoaderRoute: typeof AuthenticatedJobsCollectionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs/$jobId': {
      id: '/_authenticated/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof AuthenticatedJobsJobIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoice/$paymentId': {
      id: '/_authenticated/invoice/$paymentId'
      path: '/invoice/$paymentId'
      fullPath: '/invoice/$paymentId'
      preLoaderRoute: typeof AuthenticatedInvoicePaymentIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/interview/simulator': {
      id: '/_authenticated/interview/simulator'
      path: '/interview/simulator'
      fullPath: '/interview/simulator'
      preLoaderRoute: typeof AuthenticatedInterviewSimulatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/applications/$workspaceId': {
      id: '/_authenticated/applications/$workspaceId'
      path: '/applications/$workspaceId'
      fullPath: '/applications/$workspaceId'
      preLoaderRoute: typeof AuthenticatedApplicationsWorkspaceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/jobs': {
      id: '/_authenticated/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AuthenticatedAdminJobsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/health': {
      id: '/_authenticated/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AuthenticatedAdminHealthRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/emails': {
      id: '/_authenticated/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AuthenticatedAdminEmailsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/billing': {
      id: '/_authenticated/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AuthenticatedAdminBillingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/auto-apply': {
      id: '/_authenticated/admin/auto-apply'
      path: '/auto-apply'
      fullPath: '/admin/auto-apply'
      preLoaderRoute: typeof AuthenticatedAdminAutoApplyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ai': {
      id: '/_authenticated/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AuthenticatedAdminAiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/weekly-summary': {
      id: '/api/public/hooks/weekly-summary'
      path: '/api/public/hooks/weekly-summary'
      fullPath: '/api/public/hooks/weekly-summary'
      preLoaderRoute: typeof ApiPublicHooksWeeklySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-matches': {
      id: '/api/public/hooks/refresh-matches'
      path: '/api/public/hooks/refresh-matches'
      fullPath: '/api/public/hooks/refresh-matches'
      preLoaderRoute: typeof ApiPublicHooksRefreshMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/razorpay-webhook': {
      id: '/api/public/hooks/razorpay-webhook'
      path: '/api/public/hooks/razorpay-webhook'
      fullPath: '/api/public/hooks/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicHooksRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/email-diagnostic': {
      id: '/api/public/hooks/email-diagnostic'
      path: '/api/public/hooks/email-diagnostic'
      fullPath: '/api/public/hooks/email-diagnostic'
      preLoaderRoute: typeof ApiPublicHooksEmailDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/discover-jobs': {
      id: '/api/public/hooks/discover-jobs'
      path: '/api/public/hooks/discover-jobs'
      fullPath: '/api/public/hooks/discover-jobs'
      preLoaderRoute: typeof ApiPublicHooksDiscoverJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-apply-events': {
      id: '/api/public/hooks/auto-apply-events'
      path: '/api/public/hooks/auto-apply-events'
      fullPath: '/api/public/hooks/auto-apply-events'
      preLoaderRoute: typeof ApiPublicHooksAutoApplyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/jobs/collections/$collectionId': {
      id: '/_authenticated/jobs/collections/$collectionId'
      path: '/$collectionId'
      fullPath: '/jobs/collections/$collectionId'
      preLoaderRoute: typeof AuthenticatedJobsCollectionsCollectionIdRouteImport
      parentRoute: typeof AuthenticatedJobsCollectionsRoute
    }
    '/_authenticated/applications/$workspaceId/agent': {
      id: '/_authenticated/applications/$workspaceId/agent'
      path: '/agent'
      fullPath: '/applications/$workspaceId/agent'
      preLoaderRoute: typeof AuthenticatedApplicationsWorkspaceIdAgentRouteImport
      parentRoute: typeof AuthenticatedApplicationsWorkspaceIdRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAiRoute: typeof AuthenticatedAdminAiRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAutoApplyRoute: typeof AuthenticatedAdminAutoApplyRoute
  AuthenticatedAdminBillingRoute: typeof AuthenticatedAdminBillingRoute
  AuthenticatedAdminEmailsRoute: typeof AuthenticatedAdminEmailsRoute
  AuthenticatedAdminHealthRoute: typeof AuthenticatedAdminHealthRoute
  AuthenticatedAdminJobsRoute: typeof AuthenticatedAdminJobsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAiRoute: AuthenticatedAdminAiRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminAutoApplyRoute: AuthenticatedAdminAutoApplyRoute,
  AuthenticatedAdminBillingRoute: AuthenticatedAdminBillingRoute,
  AuthenticatedAdminEmailsRoute: AuthenticatedAdminEmailsRoute,
  AuthenticatedAdminHealthRoute: AuthenticatedAdminHealthRoute,
  AuthenticatedAdminJobsRoute: AuthenticatedAdminJobsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedApplicationsWorkspaceIdRouteChildren {
  AuthenticatedApplicationsWorkspaceIdAgentRoute: typeof AuthenticatedApplicationsWorkspaceIdAgentRoute
}

const AuthenticatedApplicationsWorkspaceIdRouteChildren: AuthenticatedApplicationsWorkspaceIdRouteChildren =
  {
    AuthenticatedApplicationsWorkspaceIdAgentRoute:
      AuthenticatedApplicationsWorkspaceIdAgentRoute,
  }

const AuthenticatedApplicationsWorkspaceIdRouteWithChildren =
  AuthenticatedApplicationsWorkspaceIdRoute._addFileChildren(
    AuthenticatedApplicationsWorkspaceIdRouteChildren,
  )

interface AuthenticatedJobsCollectionsRouteChildren {
  AuthenticatedJobsCollectionsCollectionIdRoute: typeof AuthenticatedJobsCollectionsCollectionIdRoute
}

const AuthenticatedJobsCollectionsRouteChildren: AuthenticatedJobsCollectionsRouteChildren =
  {
    AuthenticatedJobsCollectionsCollectionIdRoute:
      AuthenticatedJobsCollectionsCollectionIdRoute,
  }

const AuthenticatedJobsCollectionsRouteWithChildren =
  AuthenticatedJobsCollectionsRoute._addFileChildren(
    AuthenticatedJobsCollectionsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAgentRoute: typeof AuthenticatedAgentRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedCoachRoute: typeof AuthenticatedCoachRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLearningRoute: typeof AuthenticatedLearningRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedOutreachRoute: typeof AuthenticatedOutreachRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRoadmapRoute: typeof AuthenticatedRoadmapRoute
  AuthenticatedSalaryRoute: typeof AuthenticatedSalaryRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTrackerRoute: typeof AuthenticatedTrackerRoute
  AuthenticatedApplicationsWorkspaceIdRoute: typeof AuthenticatedApplicationsWorkspaceIdRouteWithChildren
  AuthenticatedInterviewSimulatorRoute: typeof AuthenticatedInterviewSimulatorRoute
  AuthenticatedInvoicePaymentIdRoute: typeof AuthenticatedInvoicePaymentIdRoute
  AuthenticatedJobsJobIdRoute: typeof AuthenticatedJobsJobIdRoute
  AuthenticatedJobsCollectionsRoute: typeof AuthenticatedJobsCollectionsRouteWithChildren
  AuthenticatedJobsSavedRoute: typeof AuthenticatedJobsSavedRoute
  AuthenticatedResumeReviewResumeIdRoute: typeof AuthenticatedResumeReviewResumeIdRoute
  AuthenticatedResumesResumeIdRoute: typeof AuthenticatedResumesResumeIdRoute
  AuthenticatedApplicationsIndexRoute: typeof AuthenticatedApplicationsIndexRoute
  AuthenticatedJobsIndexRoute: typeof AuthenticatedJobsIndexRoute
  AuthenticatedResumesIndexRoute: typeof AuthenticatedResumesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAgentRoute: AuthenticatedAgentRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedCoachRoute: AuthenticatedCoachRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLearningRoute: AuthenticatedLearningRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedOutreachRoute: AuthenticatedOutreachRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRoadmapRoute: AuthenticatedRoadmapRoute,
  AuthenticatedSalaryRoute: AuthenticatedSalaryRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTrackerRoute: AuthenticatedTrackerRoute,
  AuthenticatedApplicationsWorkspaceIdRoute:
    AuthenticatedApplicationsWorkspaceIdRouteWithChildren,
  AuthenticatedInterviewSimulatorRoute: AuthenticatedInterviewSimulatorRoute,
  AuthenticatedInvoicePaymentIdRoute: AuthenticatedInvoicePaymentIdRoute,
  AuthenticatedJobsJobIdRoute: AuthenticatedJobsJobIdRoute,
  AuthenticatedJobsCollectionsRoute:
    AuthenticatedJobsCollectionsRouteWithChildren,
  AuthenticatedJobsSavedRoute: AuthenticatedJobsSavedRoute,
  AuthenticatedResumeReviewResumeIdRoute:
    AuthenticatedResumeReviewResumeIdRoute,
  AuthenticatedResumesResumeIdRoute: AuthenticatedResumesResumeIdRoute,
  AuthenticatedApplicationsIndexRoute: AuthenticatedApplicationsIndexRoute,
  AuthenticatedJobsIndexRoute: AuthenticatedJobsIndexRoute,
  AuthenticatedResumesIndexRoute: AuthenticatedResumesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  GoRoute: GoRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  PHandleRoute: PHandleRoute,
  ApiPublicHooksAutoApplyEventsRoute: ApiPublicHooksAutoApplyEventsRoute,
  ApiPublicHooksDiscoverJobsRoute: ApiPublicHooksDiscoverJobsRoute,
  ApiPublicHooksEmailDiagnosticRoute: ApiPublicHooksEmailDiagnosticRoute,
  ApiPublicHooksRazorpayWebhookRoute: ApiPublicHooksRazorpayWebhookRoute,
  ApiPublicHooksRefreshMatchesRoute: ApiPublicHooksRefreshMatchesRoute,
  ApiPublicHooksWeeklySummaryRoute: ApiPublicHooksWeeklySummaryRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
